spring.application.name=authentication
# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/spring-security
spring.datasource.username=postgres
spring.datasource.password=hadjer777
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate (if using Spring Data JPA)
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# OAUTH 2.0 configurations
# ===== Google OAuth2 Client Registration =====
spring.security.oauth2.client.registration.github.client-id=
spring.security.oauth2.client.registration.github.client-secret=
spring.security.oauth2.client.registration.github.scope=read:user,user:email

# ===== Frontend URL, for redirecting after login =====
app.frontend-url=http://localhost:4200

app.jwt.secret=

