spring.application.name=authentication
# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/spring-security
spring.datasource.username=postgres
spring.datasource.password=hadjer777
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate (if using Spring Data JPA)
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
